//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class AtlasEntities : DbContext
{
    public AtlasEntities()
        : base("name=AtlasEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<donetask> donetasks { get; set; }
    public virtual DbSet<project> projects { get; set; }
    public virtual DbSet<task> tasks { get; set; }
    public virtual DbSet<user> users { get; set; }
}
